### ISSUE TITLE
How to interpret short train-short-new.conllu

### ISSUE THREAD

**Issue by juditacs** [NeldaKote/Albanian-POS#2]
Thank you for this corpus.

How should I interpret the train file with extremely short sentences? What is the source of this file and why aren't longer sentences included in the train file?

**Comment by NeldaKote** [comment]
There are two train files, train-short, and tain-without-short. As soon as possible, I will upload the instruction, how we have collected and annotated the corpora.

**Comment by juditacs** [comment]
Thanks, I see the one with long sentences now.
